config/routes.rb
Rails.application.routes.draw do
	root 'notices#index'
  devise_for :users
  resources :categories
  resources :notices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      elsif user.admin? == false
        can :manage, Notice, :user_id => user.id
        can :read, Category
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :title, presence: true, length: {maximum: 140}

	has_many :notices
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  belongs_to :category

	validates :title, 
						presence: true, 
						length: {maximum: 140}
	validates :content, :contact_details,
						presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true, length: {maximum: 50}
	
	has_many :notices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :admin, :user])
  end

  rescue_from CanCan::AccessDenied do |exception|
		render :file => "#{Rails.root}/public/403.html.erb", :status => 403, :layout => false
		## to avoid deprecation warnings with Rails 3.2.x (and incidentally using Ruby 1.9.3 hash syntax)
		## this render call should be:
		# render file: "#{Rails.root}/public/403", formats: [:html], status: 403, layout: false
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  load_and_authorize_resource

  def index
    @notices = Notice.all
  end

  def show
    
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = Notice.new(notice_params)
    if @notice.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @notice = Notice.find(params[:id])
  end

  def update
    @notice = Notice.find(params[:id])

    if @notice.update(notice_params)
      redirect_to [:admin, @notice]
    else
      render 'edit'
    end
  end

  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy
    redirect_to root_path
  end

  private

  def notice_params
    params.require(:notice).permit(:title, :content, :contact_details, :user_id, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="row">    
  <%= render 'shared/categories' %>
</div>

app/views/categories/new.html.erb
<h2>Add new category</h2>
<%= simple_form_for @category do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <div class="form-group">
      <%= f.input :title, required: true, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Done", class: "btn btn-default"  %>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="row">
	<%= render 'shared/categories' %>
	<div class="col-md-5">
		<ul class="list-group">
		  <% @category.notices.each do |notice| %>
		    <li class="list-group-item">
		      <span>Category: <u><%= notice.category.title.capitalize %></u></span></br>
		      <span><u><%= notice.title %></u></span></br>
		      <span><%= notice.content %></span></br>
		      <span>by: <%= notice.user.name %></span></br>
		    </li>
		  <% end %>
		</ul>		
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to 'Shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <p class="navbar-text">
            <%= link_to 'Create notice', new_notice_path %>
          </p>
          <p class="navbar-text">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          </p>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoticeBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <%= render 'layouts/navbar' %>
	  <div class="container">
	    <%= yield %>
	  </div>
  </body>
</html>

app/views/notices/_form.html.erb
<%= simple_form_for @notice do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <div class="form-group">
      <%= f.input :title, required: true, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.input :content, required: true, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.input :contact_details, required: true, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.association :category, include_blank: false, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.hidden_field :user_id, value: current_user.id, input_html: { class: 'form-control' } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Done", class: "btn btn-default"  %>
    </div>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h2>Edit new category</h2>
<%= render 'form' %>

app/views/notices/index.html.erb
<div class="row">
  <%= render 'shared/categories' %>
  <div class="col-md-5">
    <ul class="list-group">
      <% @notices.each do |notice| %>
        <li class="list-group-item">
          <span>Category: <u><%= notice.category.title.capitalize %></u></span></br>
          <span><u><%= link_to notice.title, notice_path(notice) %></u></span></br>
          <span><%= notice.content %></span></br>
          <span>by: <%= notice.user.name %></span></br>
        </li>
      <% end %>
    </ul>   
  </div>
</div>

app/views/notices/new.html.erb
<h2>Add new notice</h2>
<%= render 'form' %>

app/views/notices/show.html.erb
<h1><%= @notice.title %></h1>
<p><%= @notice.content %></p>
<p>
    Contact details: <b><%= @notice.contact_details %></b>
</p>
<p>
    <b>Category: </b> <%= @notice.category.title %>
</p>
    <%= link_to 'Edit notice', edit_notice_path, :html_options => {class: 'btn btn-default'} if can? :manage, :all %>
		<%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' }, :html_options => {class: 'btn btn-default'} if can? :manage, :all %>
<span class="btn btn-default">
    <%= link_to 'Back to list', root_path %>
</span>

app/views/shared/_categories.html.erb
<div class="col-md-4">
  <div class="list-group">
    <a href="#" class="list-group-item list-group-item-success">
      Categories
    </a>
    <%= link_to "All categories", root_path, class: 'list-group-item' %>
    <% Category.all.each do |category| %>
      <%= link_to category.title, category_path(category), class: 'list-group-item' %>

    <% end %>
  </div>
</div>